---
# Headless service for StatefulSet DNS. This ensures that the api gateway can address server replicas by a fixed name.
apiVersion: v1
kind: Service
metadata:
  name: openhands
spec:
  clusterIP: None
  selector:
    app: openhands
  ports:
  - port: 3000
    targetPort: 3000

---
# API Gateway deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      # custom label
      nodeSelector:
        node-group: gateway
      containers:
      - name: api-gateway
        image: sumanthrh/oh-api-gateway:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: REPLICA_COUNT
          value: "8"
        - name: BACKEND_SERVICE
          value: "openhands"
        - name: BACKEND_PORT
          value: "3000"
        - name: NAMESPACE
          value: "default"
        resources:
          requests:
            # Note: This can be somewhat overprovisioned. Adjust this as needed.
            cpu: "3000m"    # 3 cores
            memory: "8Gi"
          limits:
            cpu: "3200m"
            memory: "14Gi"

---
# LoadBalancer service for API Gateway
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
  - port: 3000
    targetPort: 3000
